### PR TITLE
Add NSX Management Proxy v0.2.1

### PR DESCRIPTION
**Pull request by Atish-iaf**
Fix dynamic HTTP CONNECT proxy for NSX-RPC traffic.

Dynamic HTTP CONNECT proxy didn't work in recent release 0.2 after we upgraded to Envoy v1.30 as there is a behaviour change in recent Envoy release. It will forward the client HTTP CONNECT request by default to the upstream servers.
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-upgradeconfig
This behaviour change resulted in connection failure for NSX-RPC traffic.

This behaviour change is not what we want. We want Envoy to remove the client HTTP CONNECT request and forward the raw traffic which comes after the HTTP CONNECT request. We fixed this by explicitly adding an empty connect_config. 
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-upgradeconfig-connectconfig

### CODE REVIEW

**Comment by Atish-iaf** [comment]
Hi @fstrudel
Please help to review this PR.
Thanks

**Review by edwardbadboy — APPROVED** [review]
Looks good to me. (Zhengsheng Zhou)

**Comment by fstrudel** [comment]
Is there more that you can add for the description to explain what issue was there and what were the symptoms?

**Review by fstrudel — APPROVED** [review]

**Comment by Atish-iaf** [comment]
> Is there more that you can add for the description to explain what issue was there and what were the symptoms?

Description updated. Thanks

**Pull request merged**
